!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  acc_lim_theta: 1.0
  acc_lim_trans: 0.1
  acc_lim_x: 1.0
  acc_lim_y: 1.0
  angular_sim_granularity: 0.017
  forward_point_distance: 0.325
  goal_distance_bias: 1.0
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      acc_lim_theta: 1.0
      acc_lim_trans: 0.1
      acc_lim_x: 1.0
      acc_lim_y: 1.0
      angular_sim_granularity: 0.017
      forward_point_distance: 0.325
      goal_distance_bias: 1.0
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      max_scaling_factor: 0.2
      max_vel_theta: 1.0
      max_vel_trans: 0.5
      max_vel_x: 0.3
      max_vel_y: 0.3
      min_vel_theta: 0.4
      min_vel_trans: 0.0
      min_vel_x: -0.3
      min_vel_y: -0.3
      name: Default
      occdist_scale: 0.01
      oscillation_reset_angle: 0.2
      oscillation_reset_dist: 0.05
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      path_distance_bias: 0.5
      prune_plan: true
      restore_defaults: false
      scaling_speed: 0.25
      sim_granularity: 0.025
      sim_time: 1.0
      state: true
      stop_time_buffer: 0.2
      theta_stopped_vel: 0.1
      trans_stopped_vel: 0.1
      twirling_scale: 0.0
      type: ''
      use_dwa: true
      vth_samples: 20
      vx_samples: 10
      vy_samples: 10
      xy_goal_tolerance: 0.05
      yaw_goal_tolerance: 0.05
    state: []
  max_scaling_factor: 0.2
  max_vel_theta: 1.0
  max_vel_trans: 0.5
  max_vel_x: 0.3
  max_vel_y: 0.3
  min_vel_theta: 0.4
  min_vel_trans: 0.0
  min_vel_x: -0.3
  min_vel_y: -0.3
  occdist_scale: 0.01
  oscillation_reset_angle: 0.2
  oscillation_reset_dist: 0.05
  path_distance_bias: 0.5
  prune_plan: true
  restore_defaults: false
  scaling_speed: 0.25
  sim_granularity: 0.025
  sim_time: 1.0
  stop_time_buffer: 0.2
  theta_stopped_vel: 0.1
  trans_stopped_vel: 0.1
  twirling_scale: 0.0
  use_dwa: true
  vth_samples: 20
  vx_samples: 10
  vy_samples: 10
  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.05
state: []
