controller_frequency: 5.0
recovery_behaviour_enabled: true
oscillation_distance: 0.5
oscillation_timeout: 3 #change later
planner_patience: 3
controller_patience: 3
recovery_behaviors:
  - {name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}
  # - {name: step_back_recovery, type: step_back_recovery/StepBackRecovery }
  - {name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery}

GlobalPlanner: # Also see: http://wiki.ros.org/global_planner

  allow_unknown: true # Allow planner to plan through unknown space, default true
  #Needs to have track_unknown_space: true in the obstacle / voxel layer (in costmap_commons_param) to work
  default_tolerance: 0.5 # If goal in obstacle, plan to the closest point in radius default_tolerance, default 0.0
  visualize_potential: true # Specifies whether or not to visualize the potential area computed via a PointCloud2.
  use_dijkstra: true # Use dijkstra's algorithm. Otherwise, A*, default true
  use_quadratic: true # Use the quadratic approximation of the potential. Otherwise, use a simpler calculation, default true
  use_grid_path: false # Create a path that follows the grid boundaries. Otherwise, use a gradient descent method, default false
  old_navfn_behavior: false # Exactly mirror behavior of navfn, use defaults for other boolean parameters, default false
  lethal_cost: 253 # default 253
  neutral_cost: 50 # default 50
  cost_factor: 3.0 # Factor to multiply each cost from costmap by, default 3.0
  publish_potential: true # Publish Potential Costmap (this is not like the navfn pointcloud2 potential), default true

  planner_window_x: 0.0 # default 0.0
  planner_window_y: 0.0 # default 0.0
  publish_scale: 100 # Scale by which the published potential gets multiplied, default 100
  planner_costmap_publish_frequency: 0.0 # default 0.0
#  orientation_mode: 1


latch_xy_goal_tolerance: true
allow_unknown: false

DWAPlannerROS:
  # Robot configuration parameters
  acc_lim_x: 1.0
  acc_lim_y: 0
  acc_lim_theta: 3.2 #0.5

  max_vel_x: 0.3
  min_vel_x: 0.05
  max_vel_y: 0.0
  min_vel_y: 0.0

  max_vel_trans: 0.3 #Increasing to 1 - to make more narroe
  min_vel_trans: 0.1
  max_vel_theta: 0.5 
  min_vel_theta: 0.23 #Do not reduce

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.13
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: true #try true for outdoor patrol robot

  # Forward Simulation Parameters
  sim_time: 5.0
  sim_granularity: 0.1
  vx_samples: 20 
  vy_samples: 20
  vth_samples: 40 

  # Trajectory scoring parameters
  path_distance_bias: 0.05
  goal_distance_bias: 2 
  occdist_scale: 2
  forward_point_distance: 0.5
  meter_scoring: false

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05 #0.05 #How far the robot must travel in meters before oscillation flags are reset (double, default: 0.05)
  oscillation_reset_angle: 0.2 #0.20
  
  #Debug
  publish_traj_pc : true
  publish_cost_grid_pc: true
  prune_plan: true
