controller_frequency: 5.0
recovery_behaviour_enabled: true
oscillation_distance: 0.5
oscillation_timeout: 3 #change later
planner_patience: 3
controller_patience: 3
recovery_behaviors:
  - {name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}
  # - {name: step_back_recovery, type: step_back_recovery/StepBackRecovery }
  - {name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery}

GlobalPlanner: 
  allow_unknown: true # Allow planner to plan through unknown space, default true
  #Needs to have track_unknown_space: true in the obstacle / voxel layer (in costmap_commons_param) to work
  default_tolerance: 0.5 # If goal in obstacle, plan to the closest point in radius default_tolerance, default 0.0
  visualize_potential: true # Specifies whether or not to visualize the potential area computed via a PointCloud2.
  use_dijkstra: true # Use dijkstra's algorithm. Otherwise, A*, default true
  use_quadratic: true # Use the quadratic approximation of the potential. Otherwise, use a simpler calculation, default true
  use_grid_path: false # Create a path that follows the grid boundaries. Otherwise, use a gradient descent method, default false
  old_navfn_behavior: false # Exactly mirror behavior of navfn, use defaults for other boolean parameters, default false
  lethal_cost: 253 # default 253
  neutral_cost: 50 # default 50
  cost_factor: 3.0 # Factor to multiply each cost from costmap by, default 3.0
  publish_potential: true # Publish Potential Costmap (this is not like the navfn pointcloud2 potential), default true
  planner_window_x: 0.0 # default 0.0
  planner_window_y: 0.0 # default 0.0
  publish_scale: 100 # Scale by which the published potential gets multiplied, default 100
  planner_costmap_publish_frequency: 0.0 # default 0.0
#  orientation_mode: 1

latch_xy_goal_tolerance: true
allow_unknown: false


DWAPlannerROS:

  holonomic_robot: true

  # Tolerances                  Defaults
  yaw_goal_tolerance: 0.05      # 0.05
  xy_goal_tolerance:  0.05      # 0.10
  latch_xy_goal_tolerance: true # false

  # Forward simulation          Defaults
  use_dwa: true                 # true
  sim_time: 1.0                 # 1.7
  sim_granularity: 0.025        # 0.025
  angular_sim_granularity: 0.017 # 0.10 (1 degree = 0.017 rad)
  vx_samples: 3                 # 3
  vy_samples: 10                # 10
  vth_samples: 20               # 20

  # Scoring                     Defaults
  meter_scoring: false          # Is this even taken into account?
  path_distance_bias: 1.00      # 32.0
  goal_distance_bias: 0.10      # 24.0
  occdist_scale: 0.01           # 0.01
  forward_point_distance: 0.325 # 0.325
  stop_time_buffer: 0.20        # 0.20
  scaling_speed: 0.25           # 0.25
  max_scaling_factor: 0.20      # 0.20
  heading_lookahead: 0.325
  heading_scoring_timestep: 0.8
  heading_scoring: true         # Is this even taken into account?
  penalize_negative_x: false    # Is this even taken into account?

  # Acceleration and velocity limits

  # acc_limit_trans: 1.0
  acc_lim_x: 1.0                # 2.5
  acc_lim_y: 1.0                # 2.5
  acc_lim_theta: 1.0            # 3.2

  # max_trans_vel: 0.5
  # min_trans_vel: 0.1
  max_vel_x: +0.3
  min_vel_x: -0.3
  max_vel_y: +0.3
  min_vel_y: -0.3

  max_vel_trans: 0.5 #Increasing to 1 - to make more narroe
  min_vel_trans: 0.0
  max_vel_theta: 1 
  min_vel_theta: 0.4 #Do not reduce
  # Other                       Defaults
  oscillation_reset_dist: 0.05  # 0.05
  oscillation_reset_angle: 0.20 # 0.20
  prune_plan: false             # true
  trans_stopped_vel: 0.1        # 0.1
  theta_stopped_vel: 0.1          # 0.1
  publish_cost_grid_pc: true    # false